spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: postgres
    password: ROOT
    driver-class-name: org.postgresql.Driver
  messages:
    basename: lang/messages
    always-use-message-format: false
    fallback-to-system-locale: true
    encoding: utf-8
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.task5.dto
server:
  servlet:
    session:
      tracking-modes: cookie
    encoding:
      enabled: true
      force: true
#debug: true